### ISSUE TITLE
Some crashs NoClassDefFoundError and NullPointerException (need help)

### ISSUE THREAD

**Issue by Marabita** [Estimote/Android-SDK#106]
Hi all, 

Our application is using the SDK estimote and are having several errors of the same type:
We are not able to play using our devices, but is becoming critical to our application, I have serious problems to explain these crashes, you guys can help me?

The errors:

[1]
java.lang.NoClassDefFoundError
com.estimote.sdk.service.BeaconService.<init>(Unknown Source)
java.lang.Class.newInstanceImpl(Native Method)
java.lang.Class.newInstance(Class.java:1319)
android.app.ActivityThread.handleCreateService(ActivityThread.java:2684)
android.app.ActivityThread.access$1600(ActivityThread.java:162)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
android.os.Handler.dispatchMessage(Handler.java:107)
android.os.Looper.loop(Looper.java:194)
android.app.ActivityThread.main(ActivityThread.java:5371)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:525)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
dalvik.system.NativeStart.main(Native Method)

[2]
java.lang.NullPointerException
com.estimote.sdk.internal.Preconditions.checkNotNull(Preconditions.java:21)
com.estimote.sdk.service.BeaconService.startRanging(BeaconService.java:232)
com.estimote.sdk.service.BeaconService.access$1200(BeaconService.java:62)
com.estimote.sdk.service.BeaconService$IncomingHandler$1.run(BeaconService.java:473)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:135)
android.os.HandlerThread.run(HandlerThread.java:61)

[3]
java.lang.NoClassDefFoundError
com.estimote.sdk.BeaconManager.isBluetoothEnabled(Unknown Source)
<mypackage>.beacon.a.b(Unknown Source)
<mypackage>.onResume(Unknown Source)
android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1190)
android.app.Activity.performResume(Activity.java:5200)
android.app.ActivityThread.performResumeActivity(ActivityThread.java:2886)
android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2928)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
android.app.ActivityThread.access$600(ActivityThread.java:156)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loop(Looper.java:153)
android.app.ActivityThread.main(ActivityThread.java:5299)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
dalvik.system.NativeStart.main(Native Method)

Manifest declaration was:
        <service
            android:name="com.estimote.sdk.service.BeaconService"
            android:exported="false" />

I can not use the code below. Our application needs to work also for above devices from version 4.0:
        <uses-feature android:name=“android.hardware.bluetooth_le”  android:required=“true” />

I use a service to access the estimote service (yes i need this)

tks

![captura de tela 2015-03-26 as 22 22 44](https://cloud.githubusercontent.com/assets/1102623/6860417/be4d2cf2-d406-11e4-870b-813cbff910fd.png)

![captura de tela 2015-03-26 as 22 25 18](https://cloud.githubusercontent.com/assets/1102623/6860455/17de69a2-d407-11e4-802a-eb82b0caefea.png)

today before starting the estimote service I check for:
BeaconManager.hasBluetooth
BeaconManager.isBluetoothEnabled

**Comment by wiktor** [comment]
It looks like you haven't attached jar with library.

**Comment by Marabita** [comment]
Hi Wiktor,

I'm using android studio, the latest version of jar (date: Nov 12, 2014), I only added the library within the libs folder, and with the command: compile filetree (dir: 'libs', include: [' *. jar '])

Is working normal for devices with newer android (4.3 or higher) detecting beacons correctly

![captura de tela 2015-03-27 as 11 04 12](https://cloud.githubusercontent.com/assets/1102623/6869196/12c99bfc-d471-11e4-992d-8af70e36aeac.png)

**Comment by wiktor** [comment]
SDK works with Android 4.3 and above. Please do check for Android version before accessing SDK as workaround. I'll add checking for Android version to SDK later.

**Comment by Marabita** [comment]
Tks Wiktor, 
I will update my code adding control by build version.

**Comment by Marabita** [comment]
java.lang.NoClassDefFoundError
com.estimote.sdk.BeaconManager.isBluetoothEnabled(Unknown Source)
br.com.mblabs.feeto.mechanism.beacon.a.b(Unknown Source)
br.com.mblabs.feeto.presentation.HomeActivity.onResume(Unknown Source)
android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1199)
android.app.Activity.performResume(Activity.java:5277)
android.app.ActivityThread.performResumeActivity(ActivityThread.java:2633)
android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2671)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2144)
android.app.ActivityThread.access$700(ActivityThread.java:143)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loop(Looper.java:137)
android.app.ActivityThread.main(ActivityThread.java:4960)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
dalvik.system.NativeStart.main(Native Method)


any call needs to be protected?

**Comment by wiktor** [comment]
Everyone that works with BeaconManager.

**Comment by tambykojak** [comment]
Looks like this can be proguard related?

**Comment by wiktor** [comment]
@tambykojak It is not, library is not run against ProGuard. Obfuscated symbols in trace are from br.com.mblabs.feeto package which is client app.
